
blueprint:
  name: Security - Alarmo - Unifi Fingerprint Scan Disarm
  description: >
    # Alarmo - Unifi Fingerprint Scan Disarm
  
    **Version:** 2026-01-07 - Beta

    
    **Purpose:**
    This blueprint disarms your Alarmo alarm panel when a UniFi Protect G4 Doorbell fingerprint scan is detected and matches an authorized user.
    It uses a sensor that contains a JSON map of authorized users keyed by ULP ID, allowing per-user codes and names.
    If the fingerprint is authorized, the alarm is disarmed using the user’s code, and a notification plus logbook entry is created.
    If unauthorized, a warning notification and logbook entry are generated.


    - **Features:**
      - Defensive filters to ensure valid fingerprint events.
      - Per-user authorization via a sensor attribute (`users`).
      - Per-user disarm codes for Alarmo.
      - Notifications for success and failure.
      - Logbook audit trail.


    - **Inputs:**  
      - Authorized Users Sensor (must have `users` attribute with JSON).
      - UniFi G4 Doorbell Fingerprint Event entity.
      - Alarmo alarm_control_panel entity.
      - Notify service for alerts.
    Full documentation: see the README on GitHub (link below).
    

    **Readme:**
    https://github.com/Blcktape/HomeAssistant/blob/main/Blueprints/alarmo_unifi_protect_g4_fingerprint_disarm_blueprint.md
    
  source_url: https://github.com/Blcktape/HomeAssistant/blob/main/Blueprints/alarmo_unifi_protect_g4_fingerprint_disarm_blueprint.md
  
  domain: automation

  input:
    authorized_users_sensor:
      name: Authorized users sensor
      description: Sensor with 'users' attribute containing JSON of authorized users keyed by ULP ID.
      selector:
        entity:
          domain: sensor

    fingerprint_event_entity:
      name: UniFi G4 Doorbell fingerprint event
      description: Select the event entity that emits fingerprint events (usually event.camera_doorbell_fingerprint).
      selector:
        entity:
          domain: event
      default: event.camera_doorbell_fingerprint

    alarm_panel:
      name: Alarmo alarm_control_panel
      description: Select your Alarmo panel entity.
      selector:
        entity:
          domain: alarm_control_panel
      default: alarm_control_panel.alarmo

    notify_service:
      name: Notify service
      description: Notification service to use (e.g., notify.mobile_app_your_phone).
      default: notify.notify_phone
      selector:
        text:

trigger:
  - alias: Fingerprint Scan Event
    platform: event
    event_type: state_changed
    event_data:
      entity_id: !input fingerprint_event_entity

condition:
  - alias: Defensive Filter - Valid Identified Event
    condition: template
    value_template: |-
      {{
        trigger.event.data.old_state is not none and
        trigger.event.data.new_state is not none and
        not trigger.event.data.old_state.attributes.get('restored', false) and
        trigger.event.data.old_state.state != 'unavailable' and
        trigger.event.data.new_state.attributes.event_type == 'identified' and
        (trigger.event.data.new_state.attributes.ulp_id | default('')) != ''
      }}

  - alias: 5 Second Recency Filter
    condition: template
    value_template: |-
      {{ trigger.event.data.new_state.state | as_datetime(as_datetime(0)) >
         now() - timedelta(seconds=5) }}

  - alias: Alarmo must be armed
    condition: state
    entity_id: !input alarm_panel
    state:
      - armed_away
      - armed_home
      - armed_night

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_user is not none }}"
        sequence:
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: !input alarm_panel
            data:
              code: "{{ user_code }}"

          - service: !input notify_service
            data:
              title: "🔓 Alarm Disarmed"
              message: >-
                [{{ now().strftime('%H:%M:%S') }}] Alarm disarmed by fingerprint:
                {{ user_display_name }} (ULP ID: {{ scanned_ulp_id }})

          - service: logbook.log
            data:
              name: "Alarmo Audit"
              message: >-
                Disarmed by {{ user_display_name }} via fingerprint scan
              entity_id: !input alarm_panel

    default:
      - service: !input notify_service
        data:
          title: "🚨 Unknown Fingerprint"
          message: >-
            [{{ now().strftime('%H:%M:%S') }}] Fingerprint detected but not authorized.

            Name: {{ scanned_name }}
            ULP ID: {{ scanned_ulp_id }}
            Status: {{ trigger.event.data.new_state.attributes.user_status }}

      - service: logbook.log
        data:
          name: "Alarmo Audit"
          message: >-
            Unauthorized fingerprint attempt: {{ scanned_name }} (ULP ID: {{ scanned_ulp_id }})
          entity_id: !input alarm_panel

variables:
  scanned_ulp_id: "{{ trigger.event.data.new_state.attributes.ulp_id }}"
  scanned_name: "{{ trigger.event.data.new_state.attributes.full_name }}"

  authorized_users_sensor_entity: !input authorized_users_sensor
  authorized_users: >-
    {% set users_attr = state_attr(authorized_users_sensor_entity, 'users') %}
    {% if users_attr is string %}
      {{ users_attr | from_json }}
    {% elif users_attr is mapping %}
      {{ users_attr }}
    {% else %}
      {{ {} }}
    {% endif %}

  current_user: "{{ authorized_users.get(scanned_ulp_id) }}"
  user_code: "{{ current_user.code if current_user is not none else '' }}"
  user_display_name: "{{ current_user.name if current_user is not none else scanned_name }}"

mode: single
trace:
  stored_traces: 15
