
blueprint:
  name: Bosch Home Connect Dryer – Reminders & Service
  description: >
    Sends end-of-cycle notifications, tracks cycles in a Counter helper, and warns for maintenance
    based on a cycle threshold. Includes device selector for notifications and custom actions.
  domain: automation
  input:
    # ---------- Finish detection ----------
    dryer_job_state:
      name: Dryer job state (sensor)
      description: >
        Sensor that reflects the job state. Cycle is considered finished when the state contains
        any of the finish keywords. Leave empty if you only use the finished binary sensor.
      default: []
      selector:
        entity:
          filter:
            - domain: sensor

    dryer_finished_binary:
      name: Dryer finished (binary_sensor)
      description: >
        Optional. Binary sensor that turns ON when the dryer has finished. If provided, it will be
        used as an additional trigger.
      default: []
      selector:
        entity:
          filter:
            - domain: binary_sensor

    finish_keywords:
      name: Finish keywords
      description: Comma-separated keywords to detect finished state. Example: finish, finished, completed, done
      default: "finish, finished, completed, done"
      selector:
        text:

    finish_stabilize_seconds:
      name: Finish stabilization (seconds)
      description: How long the finished state must hold before actions run.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          step: 5
          unit_of_measurement: sec
          mode: slider

    # ---------- Notifications ----------
    notify_devices:
      name: Devices to notify
      description: Phones/tablets (Home Assistant Companion App) to receive notifications.
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: true

    end_title:
      name: End notification title
      default: "Dryer"
      selector:
        text:

    end_message:
      name: End notification message
      default: "The dryer cycle has finished."
      selector:
        text:

    # ---------- Service / maintenance tracking ----------
    service_counter:
      name: Service counter (counter)
      description: Counter helper that tracks the number of dryer cycles.
      selector:
        entity:
          filter:
            - domain: counter

    maintenance_threshold_cycles:
      name: Maintenance threshold (cycles)
      description: Notify when the counter reaches this number of cycles.
      default: 5
      selector:
        number:
          min: 1
          max: 50
          step: 1
          mode: slider

    maintenance_title:
      name: Maintenance notification title
      default: "Dryer maintenance"
      selector:
        text:

    maintenance_message:
      name: Maintenance notification message
      description: >
        You can reference {{ states(service_counter) }} for the current counter and
        {{ maintenance_threshold_cycles }} for the threshold.
      default: >
        Time for maintenance: the dryer has run {{ states(service_counter) | int(0) }} cycles
        (threshold {{ maintenance_threshold_cycles }}). Check lint filter/heat exchanger.
      selector:
        text:

    # ---------- Custom actions ----------
    custom_actions:
      name: Custom actions (Optional)
      description: Extra actions to run after notifications (e.g., TTS/announcements).
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input dryer_job_state
    id: finished_text

  - platform: state
    entity_id: !input dryer_finished_binary
    to: "on"
    for:
      seconds: !input finish_stabilize_seconds
    id: finished_flag

variables:
  job_state_ent: !input dryer_job_state
  finish_keywords_text: !input finish_keywords
  notify_device_list: !input notify_devices

  counter_ent: !input service_counter
  maint_threshold: !input maintenance_threshold_cycles

  title_end: !input end_title
  msg_end: !input end_message
  title_maint: !input maintenance_title
  msg_maint: !input maintenance_message

  # Parse keywords
  kw_list: >-
    {{ (finish_keywords_text | default('', true) | lower)
       | replace(';', ',')
       | split(',')
       | map('trim')
       | select('ne','')
       | list }}

  # Current job state (lowercase)
  job_state_now: >-
    {% if job_state_ent %}
      {{ states(job_state_ent) | default('', true) | lower }}
    {% else %}{{ '' }}{% endif %}

  is_finished_by_text: >-
    {% set s = job_state_now %}
    {% if s == '' or kw_list | length == 0 %}
      false
    {% else %}
      {{ (kw_list | select('in', s) | list | count) > 0 }}
    {% endif %}

condition: []

action:
  - choose:
      # A) Finished via binary_sensor
      - conditions:
          - condition: trigger
            id: finished_flag
        sequence:
          - action: counter.increment
            target: { entity_id: !input service_counter }

          # Notify each selected mobile_app device
          - variables: { _list: !input notify_devices }
          - if:
              - condition: template
                value_template: "{{ _list is iterable and (_list | count) > 0 }}"
            then:
              - repeat:
                  for_each: "{{ _list }}"
                  sequence:
                    # Use device name to build notify.mobile_app_<device_name>
                    - variables:
                        _dev_name: >-
                          {{ device_attr(repeat.item, 'name') | default('', true)
                             | lower | replace(' ', '_') | replace('-', '_') }}
                    - action: >-
                        {{ 'notify.mobile_app_' ~ _dev_name }}
                      data:
                        title: !input end_title
                        message: !input end_message

          # Maintenance check
          - if:
              - condition: template
                value_template: >-
                  {{ states(counter_ent) | int(0) >= (maint_threshold | int) }}
            then:
              - if:
                  - condition: template
                    value_template: "{{ _list is iterable and (_list | count) > 0 }}"
                then:
                  - repeat:
                      for_each: "{{ _list }}"
                      sequence:
                        - variables:
                            _dev_name: >-
                              {{ device_attr(repeat.item, 'name') | default('', true)
                                 | lower | replace(' ', '_') | replace('-', '_') }}
                        - action: >-
                            {{ 'notify.mobile_app_' ~ _dev_name }}
                          data:
                            title: !input maintenance_title
                            message: !input maintenance_message

          # Custom actions
          - choose: []
            default: !input custom_actions

      # B) Finished via text state (keywords)
      - conditions:
          - condition: trigger
            id: finished_text
          - condition: template
            value_template: "{{ is_finished_by_text }}"
        sequence:
          - delay: { seconds: !input finish_stabilize_seconds }

          # Re-check still finished by keywords
          - condition: template
            value_template: >-
              {% set cur = states(job_state_ent) | default('', true) | lower %}
              {{ kw_list | select('in', cur) | list | count > 0 }}

          - action: counter.increment
            target: { entity_id: !input service_counter }

          - variables: { _list: !input notify_devices }
          - if:
              - condition: template
                value_template: "{{ _list is iterable and (_list | count) > 0 }}"
            then:
              - repeat:
                  for_each: "{{ _list }}"
                  sequence:
                    - variables:
                        _dev_name: >-
                          {{ device_attr(repeat.item, 'name') | default('', true)
                             | lower | replace(' ', '_') | replace('-', '_') }}
                    - action: >-
                        {{ 'notify.mobile_app_' ~ _dev_name }}
                      data:
                        title: !input end_title
                        message: !input end_message

          - if:
              - condition: template
                value_template: >-
                  {{ states(counter_ent) | int(0) >= (maint_threshold | int) }}
            then:
              - if:
                  - condition: template
                    value_template: "{{ _list is iterable and (_list | count) > 0 }}"
                then:
                  - repeat:
                      for_each: "{{ _list }}"
                      sequence:
                        - variables:
                            _dev_name: >-
                              {{ device_attr(repeat.item, 'name') | default('', true)
                                 | lower | replace(' ', '_') | replace('-', '_') }}
                        - action: >-
                            {{ 'notify.mobile_app_' ~ _dev_name }}
                          data:
                            title: !input maintenance_title
                            message: !input maintenance_message

          - choose: []
            default: !input custom_actions
    default: []

mode: single
max_exceeded: silent
