tionblueprint:
  name: Bosch Home Connect Dryer – Reminders & Service
  description: >
    # Bosch Home Connect Dryer – Reminders & Service
  
    **Version:** 2026-01-08 - Beta

    
    Sends end-of-cycle notifications for a Bosch/Home Connect dryer, tracks cycles in a Counter,
    reminds to empty the dryer when the door opens, warns for maintenance based on a cycle threshold,
    and (optionally) notifies + runs custom actions when the cycle starts.
    

    **Readme:**
    https://github.com/Blcktape/HomeAssistant/tree/main/Blueprints/bosch_home_connect_dryer_reminders_and_service
  
  source_url: https://github.com/Blcktape/HomeAssistant/tree/main/Blueprints/bosch_home_connect_dryer_reminders_and_service
  domain: automation

  input:
    # ---------- Dryer identification ----------
    dryer_friendly_name:
      name: Dryer friendly name (for messages)
      description: Plain text name used in notifications.
      default: "Dryer"
      selector:
        text: {}

    # ---------- Finish detection via Operation State ----------
    operation_state_sensor:
      name: Operation state sensor
      description: >
        Select your dryer operation state sensor (values like 'inactive, ready, delayedstart, run,
        pause, actionrequired, finished, error, aborting').
      selector:
        entity:
          filter:
            - domain: sensor
            
    door_state_sensor:
      name: Door state sensor
      description: Select your dryer door state sensor (states like 'open' / 'closed' / 'locked').
      selector:
        entity:
          filter:
            - domain: sensor

    finish_stabilize_seconds:
      name: Finish stabilization (seconds)
      description: How long the finished state must hold before end actions run.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          step: 5
          unit_of_measurement: sec
          mode: slider
          
    notify_devices:
      name: Devices to notify
      description: Phones/tablets (Home Assistant Companion App) to receive notifications.
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: true

    # ---------- Cycle start notification ----------
    start_notifications_section:
      name: Start Notification
      icon: mdi:play-circle
      collapsed: true
      input:
        include_start_notify:
          name: Enable start notification
          description: Toggle to send a notification when the cycle starts (run/delayedstart).
          default: false
          selector:
            boolean: {}
        start_title:
          name: Start notification title
          default: "Dryer"
          selector:
            text: {}
        start_message:
          name: Start notification message
          default: "Cycle started."
          selector:
            text: {}

    # ---------- End notifications ----------
    # ---------- Door reminder to empty the dryer ----------
    end_notifications_section:
      name: End Notification
      icon: mdi:play-circle
      collapsed: true
      input:
        end_title:
          name: End notification title
          default: "Dryer"
          selector:
            text: {}
        end_message:
          name: End notification message
          default: "Cycle has finished."
          selector:
            text: {}
        empty_dryer_title:
          name: Empty reminder title
          default: "Empty Dryer"
          selector:
            text: {}
        empty_dryer_message:
          name: Empty reminder message
          default: "Dryer door opened. Please empty the lint filter and remove laundry."
          selector:
            text: {}

    # ---------- Service / maintenance tracking ----------
    maintenance_notifications_section:
      name: Maintenance Notification
      icon: mdi:play-circle
      collapsed: true
      input:
        service_counter:
          name: Service counter (counter)
          description: Counter helper that tracks the number of dryer cycles.
          selector:
            entity:
              filter:
                - domain: counter
        maintenance_threshold_cycles:
          name: Maintenance threshold (cycles)
          description: Notify when the counter reaches this number of cycles.
          default: 5
          selector:
            number:
              min: 1
              max: 50
              step: 1
              mode: slider
        maintenance_title:
          name: Maintenance notification title
          default: "Dryer maintenance"
          selector:
            text: {}
        maintenance_message:
          name: Maintenance notification message
          description: >
            You can reference {{ states(service_counter) }} for the current counter and
            {{ maintenance_threshold_cycles }} for the threshold.
          default: >
            The dryer has run {{ states(service_counter) | int(0) }} cycles (threshold {{ maintenance_threshold_cycles }}).
            Time for routine maintenance.
          selector:
            text: {}

    # ---------- Custom actions ----------
    custom_actions_section:
      name: Custom Actions
      icon: mdi:play-circle
      collapsed: true
      input:
        start_custom_actions:
          name: Custom actions on start (Optional)
          description: Extra actions to run when the cycle starts (e.g., TTS/announcements).
          default: []
          selector:
            action: {}
        end_custom_actions:
          name: Custom actions after end (Optional)
          description: Extra actions to run after end/maintenance notifications (e.g., TTS/announcements).
          default: []
          selector:
            action: {}

# ---------- Triggers ----------
trigger:
  # A) Operation state changes (handles both start and finish)
  - platform: state
    entity_id: !input operation_state_sensor
    id: op_state_changed

  # B) Door opened -> empty reminder
  - platform: state
    entity_id: !input door_state_sensor
    id: door_state_changed

# ---------- Variables ----------
variables:
  # Entity inputs
  op_state_ent: !input operation_state_sensor
  door_state_ent: !input door_state_sensor

  # Notification devices
  notify_device_list: !input notify_devices

  # Counter / maintenance
  counter_ent: !input service_counter
  maint_threshold: !input maintenance_threshold_cycles

  # Titles & messages (inputs)
  title_end_in: !input end_title
  msg_end_in: !input end_message
  title_maint_in: !input maintenance_title
  msg_maint_in: !input maintenance_message
  title_empty_in: !input empty_dryer_title
  msg_empty_in: !input empty_dryer_message
  title_start_in: !input start_title
  msg_start_in: !input start_message

  dryer_friendly_name: !input dryer_friendly_name
  include_start_notify: !input include_start_notify

  # BAKED-IN words (no split/filter required)
  finished_word: "finished"
  door_open_word: "open"

  # Start detection words (baked-in)
  start_words: >-
    {{ ['run', 'delayedstart'] }}

  # Current states (lowercased)
  op_state_now: >-
    {% if op_state_ent %}
      {{ states(op_state_ent) | default('', true) | lower }}
    {% else %}{{ '' }}{% endif %}
  door_state_now: >-
    {% if door_state_ent %}
      {{ states(door_state_ent) | default('', true) | lower }}
    {% else %}{{ '' }}{% endif %}

  # Boolean checks
  is_finished_by_op_state: >-
    {% set s = op_state_now %}
    {{ finished_word in s }}
  is_door_open: >-
    {% set d = door_state_now %}
    {{ d == door_open_word }}
  is_started_by_op_state: >-
    {% set s = op_state_now %}
    {{ s in start_words }}

  # Compose titles/messages with friendly fallback
  title_end: >-
    {% set t = title_end_in | default('', true) %}
    {{ t if t | length > 0 else dryer_friendly_name }}
  msg_end: >-
    {% set m = msg_end_in | default('', true) %}
    {{ m if m | length > 0 else (dryer_friendly_name ~ ' cycle has finished.') }}

  title_maint: >-
    {% set tm = title_maint_in | default('', true) %}
    {{ tm if tm | length > 0 else ('Maintenance ' ~ dryer_friendly_name) }}
  msg_maint: >-
    {% set mm = msg_maint_in | default('', true) %}
    {{ mm if mm | length > 0 else
       ('The dryer has run ' ~ (states(counter_ent) | int(0)) ~ ' cycles (threshold ' ~ (maint_threshold | int)
        ~ '). Time for routine maintenance.') }}

  title_empty: >-
    {% set te = title_empty_in | default('', true) %}
    {{ te if te | length > 0 else ('Empty ' ~ dryer_friendly_name) }}
  msg_empty: >-
    {% set me = msg_empty_in | default('', true) %}
    {{ me if me | length > 0 else (dryer_friendly_name ~ ' door opened. Please empty the lint filter and remove laundry.') }}

  title_start: >-
    {% set ts = title_start_in | default('', true) %}
    {{ ts if ts | length > 0 else dryer_friendly_name }}
  msg_start: >-
    {% set ms = msg_start_in | default('', true) %}
    {{ ms if ms | length > 0 else ('Cycle started.') }}

condition: []

# ---------- Actions ----------
action:
  - choose:
      # A) FINISH path (operation state indicates finished)
      - conditions:
          - condition: trigger
            id: op_state_changed
          - condition: template
            value_template: "{{ is_finished_by_op_state }}"
        sequence:
          # Stabilize window
          - delay:
              seconds: !input finish_stabilize_seconds

          # Re-check still finished
          - condition: template
            value_template: >-
              {% set cur = states(op_state_ent) | default('', true) | lower %}
              {{ finished_word in cur }}

          # Increment cycle counter
          - action: counter.increment
            target:
              entity_id: !input service_counter

          # Notify devices (end message)
          - variables:
              _list: !input notify_devices
          - if:
              - condition: template
                value_template: "{{ _list is iterable and (_list | count) > 0 }}"
            then:
              - repeat:
                  for_each: "{{ _list }}"
                  sequence:
                    - variables:
                        _dev_name: >-
                          {{ device_attr(repeat.item, 'name') | default('', true)
                             | lower | replace(' ', '_') | replace('-', '_') }}
                    - action: >-
                        {{ 'notify.mobile_app_' ~ _dev_name }}
                      data:
                        title: "{{ title_end }}"
                        message: "{{ msg_end }}"

          # Maintenance check
          - if:
              - condition: template
                value_template: >-
                  {{ states(counter_ent) | int(0) >= (maint_threshold | int) }}
            then:
              - if:
                  - condition: template
                    value_template: "{{ _list is iterable and (_list | count) > 0 }}"
                then:
                  - repeat:
                      for_each: "{{ _list }}"
                      sequence:
                        - variables:
                            _dev_name: >-
                              {{ device_attr(repeat.item, 'name') | default('', true)
                                 | lower | replace(' ', '_') | replace('-', '_') }}
                        - action: >-
                            {{ 'notify.mobile_app_' ~ _dev_name }}
                          data:
                            title: "{{ title_maint }}"
                            message: "{{ msg_maint }}"

          # Custom actions after end
          - choose: []
            default: !input end_custom_actions

      # B) START path (operation state indicates started: run/delayedstart)
      - conditions:
          - condition: trigger
            id: op_state_changed
          - condition: template
            value_template: "{{ is_started_by_op_state }}"
        sequence:
          # Optional start notification
          - if:
              - condition: template
                value_template: "{{ include_start_notify }}"
            then:
              - variables:
                  _list: !input notify_devices
              - if:
                  - condition: template
                    value_template: "{{ _list is iterable and (_list | count) > 0 }}"
                then:
                  - repeat:
                      for_each: "{{ _list }}"
                      sequence:
                        - variables:
                            _dev_name: >-
                              {{ device_attr(repeat.item, 'name') | default('', true)
                                 | lower | replace(' ', '_') | replace('-', '_') }}
                        - action: >-
                            {{ 'notify.mobile_app_' ~ _dev_name }}
                          data:
                            title: "{{ title_start }}"
                            message: "{{ msg_start }}"

          # Custom actions on start (if provided)
          - choose: []
            default: !input start_custom_actions

      # C) DOOR OPEN path -> empty reminder (only when op_state says finished)
      - conditions:
          - condition: trigger
            id: door_state_changed
          - condition: template
            value_template: "{{ is_door_open }}"
          - condition: template
            value_template: "{{ is_finished_by_op_state }}"
        sequence:
          - variables:
              _list: !input notify_devices
          - if:
              - condition: template
                value_template: "{{ _list is iterable and (_list | count) > 0 }}"
            then:
              - repeat:
                  for_each: "{{ _list }}"
                  sequence:
                    - variables:
                        _dev_name: >-
                          {{ device_attr(repeat.item, 'name') | default('', true)
                             | lower | replace(' ', '_') | replace('-', '_') }}
                    - action: >-
                        {{ 'notify.mobile_app_' ~ _dev_name }}
                      data:
                        title: "{{ title_empty }}"
                        message: "{{ msg_empty }}"
    default: []

mode: single
max_exceeded: silent
